import { Router } from "express";

import AuthRoutes from "./auth.routes.js";
import EmployeeRoutes from "./employee.routes.js";
import EmployeeUnavailabilityRoutes from "./employeeUnavailability.routes.js";
import SessionRoutes from "./session.routes.js";
import PositionRoutes from "./position.routes.js";
import DepartmentRoutes from "./department.routes.js";
import CalendarRoutes from "./calendar.routes.js";
import PersonalAvailabilityRoutes from "./personalAvailability.routes.js";
import ShiftRoutes from "./shift.routes.js";
import ShiftAssignmentRoutes from "./shiftAssignment.routes.js";
import ShiftTaskListRoutes from "./shiftTaskList.routes.js";
import ShiftTaskListStatusRoutes from "./shiftTaskListStatus.routes.js";
import TaskRoutes from "./task.routes.js";
import TaskListRoutes from "./taskList.routes.js";
import SettingRoutes from "./setting.routes.js";
import SettingValueRoutes from "./settingValue.routes.js";
import SwapRequestRoutes from "./swapRequest.routes.js";
import EventRoutes from "./event.routes.js";
import ManagerDepartmentRoutes from "./managerDepartment.routes.js";
import EmployeeDepartmentRoutes from "./employeeDepartment.routes.js";
import DepartmentAccessRequestRoutes from "./departmentAccessRequest.routes.js";
import PositionEmployeeRoutes from "./positionEmployee.routes.js";
import PositionTaskListRoutes from "./positionTaskList.routes.js";
import TemplateRoutes from "./template.routes.js";
import TemplateShiftRoutes from "./templateShift.routes.js";
import TemplateShiftEmployeeRoutes from "./templateShiftEmployee.routes.js";
import TemplateShiftTaskListRoutes from "./templateShiftTaskList.routes.js";
import TemplateApplicationRoutes from "./templateApplication.routes.js";
import TemplateApplicationShiftRoutes from "./templateApplicationShift.routes.js";

const router = Router();

router.use("/", AuthRoutes);
router.use("/employees", EmployeeRoutes);
router.use("/employee-unavailability", EmployeeUnavailabilityRoutes);
router.use("/sessions", SessionRoutes);
router.use("/position", PositionRoutes);
router.use("/departments", DepartmentRoutes);
router.use("/calendar", CalendarRoutes);
router.use("/personal-availability", PersonalAvailabilityRoutes);
router.use("/shifts", ShiftRoutes);
router.use("/shift-assignments", ShiftAssignmentRoutes);
router.use("/shift-task-lists", ShiftTaskListRoutes);
router.use("/shift-task-list-status", ShiftTaskListStatusRoutes);
router.use("/tasks", TaskRoutes);
router.use("/task-lists", TaskListRoutes);
router.use("/settings", SettingRoutes);
router.use("/setting-values", SettingValueRoutes);
router.use("/swap-requests", SwapRequestRoutes);
router.use("/events", EventRoutes);
router.use("/manager-departments", ManagerDepartmentRoutes);
router.use("/employee-departments", EmployeeDepartmentRoutes);
router.use("/department-access-requests", DepartmentAccessRequestRoutes);
router.use("/position-employees",  PositionEmployeeRoutes);
router.use("/position-task-lists", PositionTaskListRoutes);
router.use("/templates",                  TemplateRoutes);
router.use("/template-shifts",            TemplateShiftRoutes);
router.use("/template-shift-employees",   TemplateShiftEmployeeRoutes);
router.use("/template-shift-task-lists",  TemplateShiftTaskListRoutes);
router.use("/template-applications",      TemplateApplicationRoutes);
router.use("/template-application-shifts", TemplateApplicationShiftRoutes);

export default router;
